# Valid TOML config file
data-path="/usr/app/data" # Path

bootnodes=["enode://99d5da0a665d5e80045375110b802c91391755a94126bd1f4d0ea0e41a67d9cefef06123728ca289adb7c525da71b52f593817d0d1e1a4d5cc342970552203dc@127.0.0.1:30303"]

rpc-http-enabled=true
rpc-http-api=["ETH","NET","IBFT"]
rpc-http-port=8548

p2p-port=30306

host-allowlist=["*"]

rpc-http-cors-origins=["all"]

# Chain
genesis-file="/usr/app/genesis.json" # Path to the custom genesis file