version: "3"
services:
  node:
    image: hyperledger/besu:latest
    container_name: "node-3"
    volumes:
      - .:/usr/app/
    command: --config-file=/usr/app/config.toml
    ports:
      - "8547:8545"
volumes:
  .: